app:
  label: cd-app
  replicaCount: 1
  image:
    repository: sample-app-k8s
    tag: latest
    pullPolicy: IfNotPresent
  containerName: cd-app
  service:
    name: cd-service
    type: LoadBalancer
    PORT: 8000
