app:
  label: cd-app
  replicaCount: 1
  image:
    repository: sample-app
    tag: 0.4.0
    pullPolicy: IfNotPresent
  containerName: cd-app
  service:
    name: cd-service
    type: NodePort
    PORT: 8000
