apiVersion: argoproj.io/v1alpha1 
kind: Rollout
metadata:
   name: {{.Release.Name}}-cd-sample-server
   namespace: {{ .Release.Namespace }}
   labels: 
     app: {{ .Values.app.label }}
spec:
  replicas: {{ .Values.app.replicaCount }}
  selector:
     matchLabels:
       app: {{ .Values.app.label }}
  template:
     metadata:
       labels:
          app: {{ .Values.app.label }}     
     spec:     
       containers:
         - name: {{.Values.app.containerName }}     
           image: "{{ .Values.app.image.repository}}:{{ .Values.app.image.tag}}"
           imagePullPolicy: {{ .Values.app.image.pullPolicy}}      
           ports: 
             - containerPort: {{ .Values.app.service.PORT }} 
  strategy:
    canary:
      steps:
       - setWeight: 10
       - pause: { duration: 20}
       - setWeight: 20
       - pause: { duration: 20}
       - setWeight: 30
       - pause: { duration: 20}
       - setWeight: 50
       - pause: { duration: 70}
       - setWeight: 80
       - pause: { duration: 80}                            
  revisionHistoryLimit: 3     