name: Run Helm Docs

on:
  push:
    branches:
      - main

jobs:
  linter-artifacthub:
    runs-on: ubuntu-latest
    container:
      image: public.ecr.aws/artifacthub/ah:v1.14.0
      options: --user 1001

    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          fetch-depth: 0
      - name: Set up Helm
        uses: azure/setup-helm@fe7b79cd5ee1e45176fcad797de68ecaf3ca4814 # v4.2.0
        with:
          version: v3.10.1 # Also update in publish.yaml

      - name: Print current working directory
        run: |
          REPO_ROOT="$(pwd)"
          echo "Repository root is $REPO_ROOT"

      - name: Print files in current working directory
        run: |
          ls -la

      - name: Run docs-testing (helm-docs)
        id: helm-docs
        run: |
          chmod +x ./scripts/helm-docs && ./scripts/helm-docs.sh
          if [[ $(git diff --stat) != '' ]]; then
            echo -e '\033[0;31mDocumentation outdated!\033[0m ❌'
            git diff --color
            exit 1
          else
            echo -e '\033[0;32mDocumentation up to date\033[0m ✔'
          fi
