name: Lint Helm Charts

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  linter-artifacthub:
    runs-on: ubuntu-latest
    container:
      image: public.ecr.aws/artifacthub/ah:v1.14.0
      options: --user 1001

    steps:
      - name: Checkout
        uses: actions/checkout@v3 # Updated to v3, latest stable version

      - name: Run ah lint
        working-directory: ./helm-chart
        run: ah lint

      - name: Make helm-docs.sh executable
        run: chmod +x ./helm-docs.sh

      - name: Run docs-testing (helm-docs)
        working-directory: ./
        id: helm-docs
        run: |
          ./helm-docs.sh
          if [[ $(git diff --stat) != '' ]]; then
            echo -e '\033[0;31mDocumentation outdated!\033[0m ❌'
            git diff --color
            exit 1
          else
            echo -e '\033[0;32mDocumentation up to date\033[0m ✔'
          fi
