name: Helm Chart CI

on:
  pull_request:
    branches:
      - main
      - test

jobs:
  lint-and-docs:
    runs-on: ubuntu-latest
    container:
      image: public.ecr.aws/artifacthub/ah:v1.14.0
      options: --user 1001

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.10.1

      - name: Print current working directory
        run: |
          REPO_ROOT="$(pwd)"
          echo "Repository root is $REPO_ROOT"

      - name: Print files in current working directory
        run: |
          ls -la

      - name: Run docs-testing (helm-docs)
        id: helm-docs
        run: |
          chmod +x ./scripts/helm-docs && ./scripts/helm-docs.sh
          if [[ $(git diff --stat) != '' ]]; then
            echo -e '\033[0;31mDocumentation outdated!\033[0m ❌'
            git diff --color
            exit 1
          else
            echo -e '\033[0;32mDocumentation up to date\033[0m ✔'
          fi

      - name: Run ah lint
        run: ah lint
