name: Semantic Release Workflow

on:
  pull_request:
    types: [closed]
    branches:
    - main

jobs:
  run-on-merge:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Run Semantic Release
      id: release
      uses: rymndhng/release-on-push-action@master
      with:
        bump_version_scheme: patch
        use_github_release_notes: true

    - name: Bump Helm Chart Version
      run: |
        echo "Got tag name ${{ steps.release.outputs.tag_name }}"
        echo "Got release version ${{ steps.release.outputs.version }}"

        # Path to the Chart.yaml file
        CHART_FILE="./helm-chart/Chart.yaml"

        # Read the current version of the chart from Chart.yaml
        CURRENT_VERSION=$(grep -E '^version:' "$CHART_FILE" | awk '{print $2}')

        # new version is the release version
        NEW_VERSION="${{ steps.release.outputs.version }}"

        # Update the version to the newer one in Chart.yaml
        sed -i "s/^version: $CURRENT_VERSION/version: $NEW_VERSION/" "$CHART_FILE"

        # Configure git for committing the version bump
        git config --global user.email "khadkakripu4@gmail.com"
        git config --global user.name "Kripu77"

        # Commit the changes
        git add "$CHART_FILE"
        
    - name: Set up Helm
      uses: azure/setup-helm@fe7b79cd5ee1e45176fcad797de68ecaf3ca4814 # v4.2.0
      with:
        version: v3.10.1 # Also update in publish.yaml

    - name: Install helm-docs plugin
      run: |
        curl -sSL https://github.com/norwoodj/helm-docs/releases/latest/download/helm-docs-linux-amd64.tar.gz | tar -xz -C /usr/local/bin helm-docs

    - name: Generate Helm Docs
      run: helm-docs

    - name: Commit and Push Helm Docs
      run: |
        git add .
        git commit -m "Update Helm docs"
        git push origin main

    - name: Install helm-docs plugin
      run: |
        curl -sSL https://github.com/norwoodj/helm-docs/releases/latest/download/helm-docs-linux-amd64.tar.gz | tar -xz -C /usr/local/bin helm-docs

    - name: Generate Helm Docs
      run: helm-docs

    - name: Commit and Push Helm Docs
      run: |
        git add .
        git commit -m "Update Helm docs"
        git push origin main
