name: Semantic Release Workflow
on:
  pull_request:
    types: [closed]
    branches:
    - main
jobs:
  run-on-merge:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Run Semantic Release
      id: release
      uses: rymndhng/release-on-push-action@master
      with:
        bump_version_scheme: patch
        use_github_release_notes: true

    - name: Bump Helm Chart Version
      run: |
        echo "Got tag name ${{ steps.release.outputs.tag_name }}"
        echo "Got release version ${{ steps.release.outputs.version }}"
        CHART_FILE="./helm-chart/Chart.yaml"
        CURRENT_VERSION=$(grep -E '^version:' "$CHART_FILE" | awk '{print $2}')
        NEW_VERSION="${{ steps.release.outputs.version }}"
        sed -i "s/^version: $CURRENT_VERSION/version: $NEW_VERSION/" "$CHART_FILE"
        git config --global user.email "khadkakripu4@gmail.com"
        git config --global user.name "Kripu77"
        git add "$CHART_FILE"
        git commit -m "Bump Helm chart version to $NEW_VERSION"

    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: v3.10.1

    - name: Install helm-docs
      run: |
        HELM_DOCS_VERSION=$(curl -s https://api.github.com/repos/norwoodj/helm-docs/releases/latest | jq -r .tag_name)
        curl -LO "https://github.com/norwoodj/helm-docs/releases/download/${HELM_DOCS_VERSION}/helm-docs_${HELM_DOCS_VERSION#v}_Linux_x86_64.tar.gz"
        tar -xzf helm-docs_${HELM_DOCS_VERSION#v}_Linux_x86_64.tar.gz
        sudo mv helm-docs /usr/local/bin/helm-docs
        helm-docs --version

    - name: Generate Helm Docs
      run: helm-docs

    - name: Commit and Push Changes
      run: |
        git add .
        git commit -m "Update Helm chart version and docs" || echo "No changes to commit"
        git push origin main
